name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
    tags: 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        omc-version: ['stable']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup OpenModelica
        uses: OpenModelica/setup-openmodelica@v1
        with:
          version: ${{ matrix.omc-version }}
          packages: |
            omc
          libraries: |
            Modelica 4.0.0
          omc-diff: true

      - name: openmodelica-library-testing
        uses: OpenModelica/openmodelica-library-testing-action@v0.1.0
        with:
          library: PNlib
          library-version: 'master'
          modelica-file: PNlib/package.mo
          omc-version: ${{ matrix.omc-version }}
          reference-files-dir: ReferenceFiles
          reference-files-extension: mat
          reference-files-delimiter: .

  deploy:
    needs: test
    permissions:
      contents: write
    if: endsWith(github.ref, 'master')
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get HTML artifact
        uses: actions/download-artifact@v4
        with:
          path: html-artifacts/
          pattern: '*.html'
          merge-multiple: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html-artifacts/
          branch: gh-pages
